name: Learn GHA

on:
 
 workflow_dispatch:
  inputs:
   environment:
    type: environment
    description: Environment selected
    required: true
   choice:
    type: boolean
    description: Deploy to devops
   choicetwo:
    type: boolean
    description: Deploy to prod
    
 
 
jobs:
   testing:
   
    environment: ${{ github.event.inputs.environment }}
    
    
      
    runs-on: ubuntu-latest
    
    steps:
   
      
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Setup Python
        uses: actions/setup-python@v4.7.0  

      - name: Display
        shell: bash
        run: |
          echo "Hello" >> $GITHUB_STEP_SUMMARY
        
      - name: Test
        env: 
         Mysecret: ${{ secrets.AZURE_CREDS }}
        
      

        shell: bash
        run: |
           pip install -r requirements.txt
           python main.py
   testing2:
   
    environment: ${{ github.event.inputs.environment }}
    
    
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Post Comment with Custom Content
        shell: pwsh
        run: |
              $url = "https://api.github.com/repos/$repoFullName/check-runs"
              $hdr = @{
                  Accept = 'application/vnd.github.antiope-preview+json'
                  Authorization = "token $ghToken"
              }
              $bdy = @{
                  name       = $report_name
                  head_sha   = $ref
                  status     = 'completed'
                  conclusion = $conclusion
                  output     = @{
                      title   = $report_title
                      summary = "This run completed at ``$([datetime]::Now)``"
                      text    = $reportData
                  }
              }
              Invoke-WebRequest -Headers $hdr $url -Method Post -Body ($bdy | ConvertTo-Json)
              
              
              



