name: Learn GHA

on:
 
 workflow_dispatch:
  inputs:
   environment:
    type: environment
    description: Environment selected
    required: true
   choice:
    type: boolean
    description: Deploy to devops
   choicetwo:
    type: boolean
    description: Deploy to prod
    
 
 
jobs:
   testing:
   
    environment: ${{ github.event.inputs.environment }}
    
    
      
    runs-on: ubuntu-latest
    
    steps:
   
      
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Setup Python
        uses: actions/setup-python@v4.7.0  
        
      - name: Test
        env: 
         Mysecret: ${{ secrets.AZURE_CREDS }}
        
      

        shell: bash
        run: |
           pip install -r requirements.txt
           python main.py
   testing2:
   
    environment: ${{ github.event.inputs.environment }}
    
    
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Post Comment with Custom Content
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Here's the custom content:\n\n${require('fs').readFileSync('table2.md', 'utf-8')}`
            });






