name: inspec output testing
on: [push, workflow_dispatch]
jobs:
   testing:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    steps:
   
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Setup Python
        uses: actions/setup-python@v4.7.0 
        with: 
           python-version: 3.11.4
        
      - name: Test 
        shell: bash
        run: |
           pip install -r requirements.txt
           python detailed.py

      - name: Test 2
        run: |
          python summarised.py > output.txt

      # - name: Adding markdown
      #   run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY

      # - name: Generate list using Markdown
      #   run: |
      #     echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
      #     echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
      #     echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
      #     echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
      #     echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
              
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' 
      # - run: |
      #     python summarised.py > output.txt
            
      - name: Adding markdown
        run: |
          echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
          echo "$(<output.txt)" >> $GITHUB_STEP_SUMMARY
      
      
      
