name: Custom Output Example


on:
  push:
    branches:
      - main

jobs:
     
  generate_output:
  
  
    runs-on: ubuntu-latest
    

    steps:
    -uses: actions/github-script@v6
     with:
        result-encoding: string
        script: return "I will be string (not JSON) encoded!"
    
