name: Custom Output Example


on: 
  push:
    branches:
      - main

jobs:
     
  generate_output:
  
  
    runs-on: ubuntu-latest
    

    steps:
    
     - name: Test Report
       uses: dorny/test-reporter@v1
       if: success() || failure()    # run this step even if previous step failed
       with:
          name: JEST Tests            # Name of the check run which will be created
          path: inspectestresults.xml    # Path to test results
          reporter: jest-Junit       # Format of test results
