name: Custom Output Example


on:
  push:
    branches:
      - main

jobs:
     
  generate_output:
  
  
    runs-on: ubuntu-latest
    

    steps:
        
    
     

      - name: Display Custom Output
        
        uses: actions/github-script@v6
        id: my-script
        with:
         result-encoding: string
         script: return "I will be string (not JSON) encoded!"
    
