name: Create Check Run

on:
  push:
    branches:
      - main

jobs:
  create_check_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Check Run
        id: create_check_run
        run: |
          # Use the GitHub Checks API to create a check run
          response=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs" \
            -d '{
              "name": "Custom Check",
              "head_sha": "${{ github.sha }}",
              "status": "in_progress",
              "output": {
                "title": "Custom Check In Progress",
                "summary": "This is a custom check in progress",
                "text": "Additional information about the check"
              }
            }')
          
          # Extract the check run ID from the response
          check_run_id=$(echo "$response" | jq -r '.id')

      - name: Finish Check Run
        run: |
          # Use the GitHub Checks API to complete the check run
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs/$check_run_id" \
            -d '{
              "status": "completed",
              "conclusion": "success",
              "completed_at": "'$(date --utc +%FT%TZ)'",
              "output": {
                "title": "Custom Check Completed",
                "summary": "Custom check completed successfully"
              }
            }'
