name: Create Check Run

on:
  push:
    branches:
      - main

jobs:
  create_check_run:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Check Run
        id: create_check_run
        run: |
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/nikhil-insight/githubactionpoc/check-runs \
              -d '{"name":"mighty_readme","head_sha": ${{ github.sha }},"status":"in_progress","external_id":"42","started_at":"2018-05-04T01:14:52Z","output":{"title":"Mighty Readme report","summary":"hi","text":"hi"}}'
                      
        
