name: Create Check Run

on:
  push:
    branches:
      - main

jobs:
  create_check_run:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Check Run
        id: create_check_run
        run: |
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/nikhil-insight/githubactionpoc/check-runs \
              -d '{
              "name": "Custom Check",
              "head_sha": "${{ github.sha }}",
              "status": "completed",
              "conclusion": "success",
              "output": {
                "title": "Custom Check Results",
                "summary": "This is a custom check with annotations"
              }'
                      
        
